"""Render the FATURA class-mapping table over the training corpus.

    python -m data.mapping_report > /tmp/table.md

The README's labelling section is generated by this, not written by hand, so the table can
never drift from what `map_fatura.py` actually does.
"""

from __future__ import annotations

import json
import zipfile
from pathlib import Path

from data.build_splits import ANNOTATION_PREFIX
from data.download import RAW_DIR
from data.map_fatura import MappingReport, map_annotation
from data.sources import FATURA
from data.split import SPLIT_DIR, load_manifest


def report_for(doc_ids: set[str], archive: Path) -> MappingReport:
    report = MappingReport()
    with zipfile.ZipFile(archive) as zf:
        for doc_id in sorted(doc_ids):
            name = f"{ANNOTATION_PREFIX}{doc_id}.json"
            report.observe(map_annotation(json.loads(zf.read(name)), name))
    return report


def main() -> int:
    archive = RAW_DIR / FATURA.filename
    train = load_manifest(SPLIT_DIR / "train.json")
    report = report_for(set(train.doc_ids), archive)
    print(report.to_markdown())
    print()
    print(
        f"Built over the {report.documents} training documents "
        f"({len(report.layouts)} layouts). Conflicts: {dict(report.conflicts) or 'none'}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
